config/routes.rb
Rails.application.routes.draw do

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  apipie

  get '/user_info_for_chat' => 'users#info_for_chat', format: :js

  scope '(:locale)' do
    get 'users/sign_up' => 'home#register'
  end

  devise_for :users, controllers: {sessions: "sessions"}

  namespace :api, defaults: {format: 'json'} do
    scope module: :v1, constraints: ApiConstraints.new(version: 1, default: true) do
      devise_for :users, only: [:sessions, :registrations ], controllers: {sessions: 'api/v1/devise/sessions', registrations: 'api/v1/devise/registrations'}
      resources :users do
        get :default_values, on: :collection
        get :search, on: :collection
        get :me, on: :collection
        get :display_contact_info, on: :collection
        post :verify_payment, on: :collection
        get :verify_account, on: :collection
        get :resend_verification_code, on: :collection
        get :subscribe_for_notification, on: :collection
        get :reset_password, on: :collection
        post :update_password, on: :collection
        post :update_profile, on: :collection
        put :update_user, on: :collection
        post :send_notification, on: :collection
      end

      resources :conversations, only: [:index, :create, :show, :destroy] do
        get :latest_messages
        post :read
        collection do
          get :unread_count
        end
      end
      resources :messages, only: [:create]
      resources :contacts, only: [:create]
      resources :feedbacks, only: [:create]
      resources :activities do
        member do
          get :join
          get :leave
        end
      end
    end
  end

  scope '(:locale)' do
    resources :users do
      post :update_payment_status
      get :get_contact_info, format: :js
      get :follow, format: :js
      get :unfollow, format: :js
    end

    resources :conversations do
      resources :messages
    end

    resources :feedbacks

    # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
    root "home#index"
    get "/register" => 'home#register'
    post "/register_user" => 'home#register_user', format: :js
    post "/verify_code" => 'home#verify_code', format: :js
    get "/verify" => 'users#verify_phone_number', as: 'new_verify'
    post '/verify' => 'users#resend_code', as: 'resend_verify'
    put '/verify' => 'users#verify_code', as: 'verify'
    get "/summary" => 'home#summary'
    get "/search" => 'home#search'
    post "/search" => 'home#search'
    get "/mydetail" => 'home#mydetail'
    get "/mysubject" => 'home#mysubject'
    get "/myenquiry" => 'home#myenquiry'
    get "/mypurchase" => 'home#mypurchase'
    get "/online-lesson" => 'home#online_lesson'
    get "/feedback_section" => 'home#feedback_section'
    get "/found-me" => 'home#found_me'
    get "/suggested-teacher" => 'home#suggested_teacher'
    get "/profile-photo" => 'home#profile_photo'
    get "/post-question" => 'home#post_question'
    get "/followers" => 'home#followers'
    get "/tags" => 'home#tags'
    get "/history" => 'home#history'
    get "/privacy" => 'home#privacy'
    get "/contactus" => 'home#contactus'
    get "/aboutus" => 'home#aboutus'
    get "/payment" => 'home#payment'
  end
end

app/controllers/api/v1/users_controller.rb
class Api::V1::UsersController < ApiController
  include Concerns::UserAuthentication
  include HomeHelper

  skip_before_action :authenticate_user, only: [:default_values, :verify_account, :resend_verification_code, :reset_password]
  skip_before_action :set_user, only: [:default_values, :verify_account, :resend_verification_code, :reset_password]
  before_action :set_user_object, only: [:show]
  before_action :set_payment, only: [:verify_payment]
  before_action :set_user_by_email, only: [:reset_password]
  before_action :validate_current_password, only: [:update_password]
  before_action :set_device_type, only: [:verify_account]
  load_and_authorize_resource

  resource_description do
    short "A user register itself, interacts with tutors, students, hobbyist and employees"
  end

  def_param_group :update_user_group do
    param :user, Hash, required: true do
      param :email, String
      param :first_name, String
      param :last_name, String
      param :password, String
      param :account_type, String, desc: "Valid account types values are in #{User::ACCOUNT_TYPES}"
      param :city, String
      param :gender, String
      param :education_level, String
      param :institution, String
      param :major, String
      param :other_major, String
      param :nationality, String
      param :work_experience, String
      param :hourly_rate, String
      param :date_of_birth, String
      param :job, String
      param :mobile_number, String
      param :bio, String
      param :other_institute, String
      param :availablity_start_time, String
      param :availablity_end_time, String
      param :hobbies, Array, of: String
      param :languages, Array, of: String
      param :latitude, Float
      param :longitude, Float
      param :teaching_interests, Array, of: String
      param :teaching_modules, Array, of: String
      param :interested_in_online_lessons, [true, false, 'true', 'false']
      param :interested_in_online_teachings, [true, false, 'true', 'false']
      param :degrees_attributes, Hash, desc: 'Degrees Attributes' do
        param :id, String
        param :name, String
        param :institution, String
        param :other_institute, String
        param :_destroy, String
      end
      param :photo_attributes, Hash, desc: 'Photo Attributes' do
        param :id, String
        param :avatar, String
        param :_destroy, String
      end
    end
  end

  api :PUT, '/update_user', "User can update its profile"
  param_group :update_user_group
  formats ['json']
  description 'User can update its profile'
  def update_user
    if @current_user.update(user_params)
      @current_user.update_openfire_user(params[:user][:password])
      render json: { user: UserSerializer.new(@current_user), message: "Profile updated successfully" }, status: :ok
    else
      render json: { user: UserSerializer.new(@current_user), message: @current_user.errors.full_messages.to_sentence }, status: :unauthorized
    end
  end

  api :POST, '/users/update_password', "Update password of given user"
  formats ['json']
  description 'Update password of given user'
  param :current_password, String, desc: "Current password of user whose password has to be changed", required: true
  param :new_password, String, desc: "New password of user which is to be set", required: true
  def update_password
    @current_user.password = params[:new_password] if params[:new_password].present?
    if @current_user.save
      @current_user.update_openfire_user(params[:user][:new_password])
      return render json: {success: true}, status: :ok
    else
      return render json: {success: false, error: @current_user.errors.full_messages.to_sentence}, status: :not_acceptable
    end
  end

  api :GET, '/users/reset_password', "Reset password of given user"
  formats ['json']
  description 'Reset password of given user'
  param :email, String, desc: "Email of user whose password has to be reset", required: true
  def reset_password
    if @user.send_reset_password_instructions
      return render json: {success: true}, status: :ok
    else
      return render json: {success: false}, status: :not_acceptable
    end
  end

  api :POST, '/users/update_profile', "Update profile of current user"
  formats ['json']
  description 'Update profile of current user'
  param :image, Object, desc: "User profile image", required: true
  def update_profile
    previous_photo = @current_user.photo
    @current_user.build_photo
    @current_user.photo.avatar = params[:image]

    if @current_user.save
      @current_user.update_openfire_user()
      previous_photo.try(:destroy)
      return render json: {success: true, image_url: @current_user.avatar_url}, status: :ok
    else
      return render json: {success: false, error: @current_user.errors.full_messages.to_sentence}, status: :not_acceptable
    end
  end

  api :GET, '/users/default_values', "Return available option values for registeration"
  formats ['json']
  description 'Return available option values for registeration'
  def default_values
    render json: {account_types: options_for_account_type, genders: options_for_gender, teaching_interests: options_for_teaching_interests, languages: options_for_languages, teaching_modules: options_for_teaching_modules, hobbies: options_for_hobbies, jobs: options_for_job, nationalities: options_for_nationality, cities: options_for_city, education_levels: options_for_education_level, institutions: options_for_institution, majors: options_for_major, time_slots: options_for_time}, status: :ok
  end

  api :GET, '/users/search', "Return searched users results"
  formats ['json']
  description 'Return searched users results'
  def search
    @q = User.ransack(params[:q])
    @users = @q.result.where.not(id: @current_user.id)
    @users = @users.page(params[:page]).per(User::PER_PAGE)
    serialized_users = @users.map { |user| UserListSerializer.new(user) }
    render json: {users: serialized_users}, status: :ok
  end

  api :GET, '/users/:id', "Return user object"
  formats ['json']
  description 'Return user object'
  def show
    @user.ratings.includes(:user)
    render json: {user: UserSerializer.new(@user)}, status: :ok
  end

  api :GET, '/users/me', "Return current user object"
  formats ['json']
  description 'Return current user object'
  def me
    render json: {user: UserSerializer.new(@current_user)}, status: :ok
  end

  api :GET, '/users/display_contact_info', "Return result to display contact info to user or not"
  formats ['json']
  description 'Return result to display contact info to user or not'
  param :user_id, String, desc: "Id of user whose contact info is to be displayed ", required: true
  def display_contact_info
    if @current_user.users_viewed.length < User::MAX_USERS_CONTACT_INFO_VIEWS || @current_user.payments.successfull.present?
      unless @current_user.users_viewed.include?(params[:user_id].to_i)
        @current_user.users_viewed.push(params[:user_id])
        @current_user.save(validate: false)
      end
      return render json: {success: true}, status: :ok
    else
      return render json: {success: false}, status: :ok
    end
  end

  api :POST, '/users/verify_payment', "Verify mobile payment from paypal"
  formats ['json']
  description 'Verify mobile payment from paypal'
  param :user_id, String, desc: "Id of user whose payment has to be verified", required: true
  def verify_payment
    @user = User.find_by(id: params[:user_id])

    if @user.present? && @user.payments.create(payment_type: "Paypal", paymentID: @payment_id, state: @payment.state, mobile_payment: true)

      if @payment.state = 'approved'
        render json: { message: "Your payment was successfull" }, status: :ok
      else
        render json: { message: "Sorry! Your payment was not successfull yet" }, status: :ok
      end
    end
  end

  api :GET, '/users/verify_account', "Verify account by code sent on user's mobile number"
  formats ['json']
  description "Verify account by code sent on user's mobile number"
  param :user_id, String, desc: "Id of user whose account has to be verified", required: true
  param :code, String, desc: "4 digits code that user received on mobile number for account verification", required: true
  def verify_account
    @user = User.find_by(id: params[:user_id])

    if @user.present? && !@user.verified? || params[:code].blank?
      if Time.now > @user.pin_sent_at.advance(minutes: 60)
        render json: { message: "Your pin has expired. Please request another." }, status: :not_acceptable
      elsif params[:code].try(:to_i) == @user.pin
        @user.update(verified: true)

        access_token = @user.generate_access_token([:device_id], @device_type)
        sign_in(:user, @user)
        return render json: {success: true, access_token: access_token, user: UserSerializer.new(@user)}, status: :accepted
      else
        render json: { message: "Sorry! This code is invalid. Please try again" }, status: :not_acceptable
      end
    else
      render json: { message: "Sorry! This code is invalid. Please try again" }, status: :not_acceptable
    end
  end

  api :GET, '/users/resend_verification_code', "Resend verification code on user's mobile number"
  formats ['json']
  description "Resend verification code on user's mobile number"
  param :user_id, String, desc: "Id of user whose account has to be verified", required: true
  def resend_verification_code
    @user = User.find_by(id: params[:user_id])

    if @user.present? && !@user.verified?
      @user.send_pin!

      return render json: {success: true, message: "We have successfully resent a verification code on your mobile number #{@user.mobile_number}. Please enter it to activate your account"}, status: :ok
    else
      render json: { message: "Sorry! This user does not exist or already been verified" }, status: :not_acceptable
    end
  end

  api :GET, '/users/subscribe_for_notification', "Subscribe user for push notification"

app/helpers/users_helper.rb
module UsersHelper
  def fetch_user_mobile_number user
    return user.mobile_number if user.mobile_number.present?
    "N/A"
  end

  def fetch_photo user, size
    return user.photo.avatar.url(size.to_sym) if user.photo.present?
    return 'prifile-image-male.png' if user.male?
    return 'prifile-image-female.png' if user.female?
    'prifile-image.jpg'
  end

  def boolean_to_human bool
    return 'Yes' if bool
    'No'
  end

  def image_for_chat user
    image = if user.blank?
      'prifile-image.jpg'
    elsif user.photo.present?
      user.photo.avatar.url(:profile)
    elsif user.male?
      'prifile-image-male.png'
    elsif user.female?
      'prifile-image-female.png'
    else
      'prifile-image.jpg'
    end

    asset_url(image)
  end
end

app/views/users/_contact_info.html.erb
<div class="modal fade contact-info" id="contact-info-modal" title="Contact Info of <%= @user.first_name %>">
  <div class="modal-header">
    <button aria-hidden="true" class="close" data-dismiss="modal" type="button">×</button>
    <h3 id="myModalLabel">Contact Info of <%= @user.first_name %></h3>
  </div>

  <% if @payment %>
    <div class="modal-body">
      <div class="row">
        <div class="col-md-12">
          You have reach maximum limit to view user's contact information. Please pay before viewing more contact informations.
        </div>
      </div>
    </div>
  <% else %>
    <div class="modal-body">
      <div class="row">
        <div class="col-md-6">
          Email:
        </div>
        <div class="col-md-6">
          <%= @user.email %>
        </div>
      </div>
      <div class="row">
        <div class="col-md-6">
          Phone:
        </div>
        <div class="col-md-6">
          <%= fetch_user_mobile_number(@user) %>
        </div>
      </div>
    </div>
  <% end %>
  <div class="modal-footer">
    <button aria-hidden="true" class="btn" data-dismiss="modal">Close</button>
    <% if @payment %>
      <%= link_to 'Proceed to payment page', payment_path(return_to_user: @user.id), class: 'btn btn-primary pull-right' %>
    <% end %>
  </div>
</div>

app/views/users/_follow_unfollow_result.html.erb
<div class="modal fade contact-info" id="follow-unfollow-modal">
  <div class="modal-header">
    <button aria-hidden="true" class="close" data-dismiss="modal" type="button" onclick="javascript:window.location.reload()" >×</button>
    <h3 id="myModalLabel"><%= @type.camelcase %> <%= @user.first_name %></h3>
  </div>

  <% if @result %>
    <div class="modal-body">
      <div class="row">
        <div class="col-md-12">
          You have successfully <%= @type %> <%= @user.username %>.
        </div>
      </div>
    </div>
  <% else %>
    Failed to <%= @type %> <%= @user.username %>.
  <% end %>
  <div class="modal-footer">
    <button aria-hidden="true" class="btn" data-dismiss="modal" onclick="javascript:window.location.reload()" >Close</button>
  </div>
</div>

app/views/users/follow.js.erb
$('#follow-unfollow-div').html('$("<%= j render(:partial => 'follow_unfollow_result') %>")');
$('#follow-unfollow-modal').modal('toggle');

app/views/users/get_contact_info.js.erb
$('#contact-info-div').html('$("<%= j render(:partial => 'contact_info', :locals => {:payment => @payment, :user => @user}) %>")');
$('#contact-info-modal').modal('toggle');

app/views/users/show.html.erb
<section class="agency-status" style="padding:50px 0">
  <div class="container">
    <div class="row">
      <div class="col-md-8 col-sm-8">
        <div class="row">
          <div class="col-md-12">
            <h2 class="redcolor"><%= @user.first_name %> (<%= @user.account_type %> in <%= @user.city %>)</h2>
          </div>
        </div>
        <div class="row">
          <div class="col-md-6 border-right-tutor profile-tutor-mb">
            <div class="row">
              <div class="col-md-6">
                <%= image_tag fetch_photo(@user, :profile), class: 'img-circle tutor_img' %>
              </div>
              <div class="col-md-6 tutor-img profile-name-center">
                <p><span class="glyphicon glyphicon-ok"></span> ID Verfied</p>
                <h4><%= @user.first_name %> (<%= @user.account_type %>)</h4>
                <p><span class="glyphicon glyphicon-map-marker"> </span> <%= @user.city %></p>
                <p><span class="glyphicon glyphicon-education"> </span> | <span class="glyphicon glyphicon-star"> </span> | <span class="glyphicon glyphicon-map-marker"> </span></p>
              </div>
            </div>
          </div>
          <div class="col-md-6 tutor-img profile-name-center">
            <p><strong><%= t('profile.feedback') %></strong></p>
            <p><b><%= t('profile.member') %></b> <%= render_date(@user.last_sign_in_at) %></p>
            <p><b><%= t('profile.last_login') %></b> <%= t('profile.four_month') %></p>
            <p><b><%= t('profile.response_rate') %></b> 90%</p>
            <p><b><%= t('profile.expected_response') %></b> <%= t('profile.one_month') %></p>
            <% if @user.student? %>
              <p><b><%= t('profile.interested_in_online_lessons') %></b> <%= boolean_to_human(@user.interested_in_online_lessons) %></p>
            <% end %>
            <% if @user.tutor? %>
              <p><b><%= t('profile.interested_in_online_teachings') %></b> <%= boolean_to_human(@user.interested_in_online_teachings) %></p>
            <% end %>
          </div>
        </div>
        <button type="button" class="btn btn-danger start-conversation" data-username="<%= @user.jid %>" data-rip="<%= @user.id %>"><span class="glyphicon glyphicon-comment"></span> <%= t('profile.chat_with') %> <%= @user.first_name %> </button>

        <%#= link_to "#{ t('profile.see_contact_info') }", user_get_contact_info_path(@user, id: @user.id, format: :js), class: "btn btn-warning", remote: true %>
        <% if current_user.follows?(@user) %>
          <%= link_to "#{ t('profile.unfollow') }", user_unfollow_path(@user, id: @user.id, format: :js), class: "btn btn-default", remote: true %>
        <% else %>
          <%= link_to "#{ t('profile.follow') }", user_follow_path(@user, id: @user.id, format: :js), class: "btn btn-info", remote: true %>
        <% end %>

        <p class="tutor-img"></p>

        <div class="row">
          <div class="col-sm-12">
            <h4><%= t('profile.about') %> <%= @user.first_name %></h4>
            <p><%= @user.bio %></p>
            <h4><%= t('profile.availability') %></h4>
            <p> <%= t('profile.availability_text') %>
            </p>
          </div>
        </div>
        <% if @user.degrees.present? %>
          <div class="row">
            <h2><%= t('profile.qualifications') %></h2>
            <div class="col-sm-12">
              <% @user.degrees.each do |degree| %>
                <div class="col-sm-3">
                  <ul>
                    <li><strong><%= degree.name %></strong></li>
                    <li><%= degree.institution %></li>
                  </ul>
                </div>
              <% end %>
            </div>
          </div>
        <% end %>
        <p class="tutor-img"></p>
        <div class="row">
          <h2><%= t('profile.feedback_for') %> <%= @user.first_name%> (<%= @feedbacks.count %>)</h2>
          <hr>
          <p><%= t('profile.review_count') %><%= @feedbacks.count %> <%= t('profile.review_for') %> <%= @user.first_name %>.</p>

          <% @feedbacks.each do |feedback| %>
            <p><b><%= feedback.user.first_name %> (<%= formatted_name_title(feedback.user.gender) %>)</b></p>
            <p><b><%= formatted_time(feedback.created_at) %></b></p>
            <p><div class="starbox starbox-<%= feedback.id %> ghosting autoupdate small"> </div><p></p></p>
            <p><%= feedback.comment %></p>
          <% end %>

          <%= form_for(@feedback) do |f| %>

            <div class="block">
              <h3><%= t('profile.provide_feedback') %></h3>
              <div class="starbox ghosting autoupdate small smooth"> </div><p></p>
            </div>

            <div class="row">
              <div class="col-md-10 col-sm-10">
                <div class="form-group">
                  <label for="exampleInputEmail1"><%= t('profile.share_feedback') %></label>
                  <%= text_area_tag(:comment, '', rows: 7, class: 'form-control', placeholder: "#{t('profile.share_feedback')}", required: true) %>
                </div>
              </div>
            </div>

            <%= hidden_field_tag 'rating', '0.5', id: 'rating-value' %>
            <%= hidden_field_tag 'rated_id', @user.id %>

            <div class="row">
              <div class="col-md-12">
                <%= f.submit t('profile.post'), {class: "btn btn-danger"} %>
              </div>
            </div>
          <% end %>

        </div>
      </div>
      <!-- col md 9 col sm 9 -->
      <div class="col-md-4 col-sm-4">
        <div class="right-side">
          <div class="search-form">
            <!-- Nav tabs -->
            <ul class="nav nav-tabs search-nav-tab" role="tablist">
              <li role="presentation" class="active"><a href="#home" aria-controls="home" role="tab" data-toggle="tab">
                <span class="glyphicon glyphicon-user" aria-hidden="true"></span> <%= t('profile.contact') %> <%= @user.first_name%> </a>
              </li>
            </ul>
            <!-- Tab panes -->
            <div class="tab-content">
              <div role="tabpanel" class="tab-pane active" id="home">
                <div class="myonline-lessons-contents">
                  <div class="form-group">
                    <div class="form-group">
                      <input type="Email" class="form-control" id="exampleInputEmail1" value="<%= current_user.email %>" placeholder="Email">
                    </div>
                  </div>
                  <div class="form-group">
                    <input type="Name" class="form-control" id="exampleInputEmail1" value="<%= current_user.first_name %>" placeholder="Name">
                  </div>
                </div>
                <div class="form-group">
                  <input type="Last Name" class="form-control" id="exampleInputEmail1" value="<%= current_user.last_name %>" placeholder="Last Name">
                </div>
                <div class="form-group">
                  <textarea name="" id="" cols="30" rows="8" class="form-control"></textarea>
                </div>
                <div class="checkbox">
                  <label>
                  <input type="checkbox"> <%= t('profile.i_agree') %> <a href="#"><%= t('profile.condition') %></a>
                  </label>
                </div>
                <div class="text-center">
                  <button type="button" class="btn btn-danger send-message-btn "><%= t('profile.send_message') %></button>
                </div>
                <div class="text-center">
                  <button type="button" class="btn btn-success black-btn"><%= t('profile.already_member') %></button>
                </div>
              </div>
            </div>
          </div>
        </div>
        <div class="right-side  my-follers-mt">
          <div class="search-form">
            <div class="tab-content">
              <h4><%= t('profile.my_followers') %></h4>
              <p><%= t('profile.no_followers') %></p>
              <h4><%= t('profile.following') %></h4>
              <p><%= t('profile.no_following') %></p>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

<div id='contact-info-div'></div>
<div id='follow-unfollow-div'></div>

<%= render 'shared/feedback_initializer' %>

app/views/users/unfollow.js.erb
$('#follow-unfollow-div').html('$("<%= j render(:partial => 'follow_unfollow_result') %>")');
$('#follow-unfollow-modal').modal('toggle');

app/views/users/verify_phone_number.html.erb
<div class="sign-in-response">
  <%= render 'shared/flash_messages' %>
</div>

<div class="clearfix"></div>

<section class="agency-status" style="padding:50px 0">
  <div class="container">
    <div class="row">
      <div class="agency-status-contents clearfix">
        <div class="col-md-6 col-md-offset-3">
          <div class="panel heading-bg">
            <div class="panel-heading">
              <h3 class="panel-title" style="color:#000;"><%= t('verify.title') %></h3>
            </div>
            <div class="panel-body">
              <%= form_tag verify_path, method: :put do %>
                <div class="form-group">
                  <label for="verification-code" class="col-sm-4 control-label"><%= t('verify.code_label') %></label>
                  <div class="col-sm-8">
                    <%= text_field_tag :code, nil, class: 'form-control', required: true %>
                  </div>
                </div>

                <div class="form-group pt-100">
                  <%= link_to t('verify.resend_code'), resend_verify_path, method: :post, class: 'btn btn-primary resend-code-btn' %>
                  <%= submit_tag t('verify.submit_code'), class: 'btn btn-success' %>
                </div>
              <% end %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>