config/routes.rb
Rails.application.routes.draw do

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  apipie

  get '/user_info_for_chat' => 'users#info_for_chat', format: :js

  scope '(:locale)' do
    get 'users/sign_up' => 'home#register'
  end

  devise_for :users, controllers: {sessions: "sessions"}

  namespace :api, defaults: {format: 'json'} do
    scope module: :v1, constraints: ApiConstraints.new(version: 1, default: true) do
      devise_for :users, only: [:sessions, :registrations ], controllers: {sessions: 'api/v1/devise/sessions', registrations: 'api/v1/devise/registrations'}
      resources :users do
        get :default_values, on: :collection
        get :search, on: :collection
        get :me, on: :collection
        get :display_contact_info, on: :collection
        post :verify_payment, on: :collection
        get :verify_account, on: :collection
        get :resend_verification_code, on: :collection
        get :subscribe_for_notification, on: :collection
        get :reset_password, on: :collection
        post :update_password, on: :collection
        post :update_profile, on: :collection
        put :update_user, on: :collection
        post :send_notification, on: :collection
      end

      resources :conversations, only: [:index, :create, :show, :destroy] do
        get :latest_messages
        post :read
        collection do
          get :unread_count
        end
      end
      resources :messages, only: [:create]
      resources :contacts, only: [:create]
      resources :feedbacks, only: [:create]
      resources :activities do
        member do
          get :join
          get :leave
        end
      end
    end
  end

  scope '(:locale)' do
    resources :users do
      post :update_payment_status
      get :get_contact_info, format: :js
      get :follow, format: :js
      get :unfollow, format: :js
    end

    resources :conversations do
      resources :messages
    end

    resources :feedbacks

    # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
    root "home#index"
    get "/register" => 'home#register'
    post "/register_user" => 'home#register_user', format: :js
    post "/verify_code" => 'home#verify_code', format: :js
    get "/verify" => 'users#verify_phone_number', as: 'new_verify'
    post '/verify' => 'users#resend_code', as: 'resend_verify'
    put '/verify' => 'users#verify_code', as: 'verify'
    get "/summary" => 'home#summary'
    get "/search" => 'home#search'
    post "/search" => 'home#search'
    get "/mydetail" => 'home#mydetail'
    get "/mysubject" => 'home#mysubject'
    get "/myenquiry" => 'home#myenquiry'
    get "/mypurchase" => 'home#mypurchase'
    get "/online-lesson" => 'home#online_lesson'
    get "/feedback_section" => 'home#feedback_section'
    get "/found-me" => 'home#found_me'
    get "/suggested-teacher" => 'home#suggested_teacher'
    get "/profile-photo" => 'home#profile_photo'
    get "/post-question" => 'home#post_question'
    get "/followers" => 'home#followers'
    get "/tags" => 'home#tags'
    get "/history" => 'home#history'
    get "/privacy" => 'home#privacy'
    get "/contactus" => 'home#contactus'
    get "/aboutus" => 'home#aboutus'
    get "/payment" => 'home#payment'
  end
end

app/views/shared/_desktop_header.html.erb
<div class="header-top hidden-sm hidden-xs clearfix">
  <div class="container">
    <div class="row">
      <div class="col-md-3">
        <address><i class="fa fa-envelope"> </i> query@geekrabb.com </address>
      </div>
      <div class="col-md-offset-6 col-md-3">
        <ul class="social-icons">
          <li><a href="#"><i class="fa fa-facebook"></i></a></li>
          <li><a href="#"><i class="fa fa-twitter"></i></a></li>
          <li><a href="#"><i class="fa fa-linkedin"></i></a></li>
          <li><a href="#"><i class="fa fa-google-plus"></i></a></li>
        </ul>

      </div>
    </div>
  </div>
</div>
<div class="clearfix"></div>

<div class="header-2 hidden-sm hidden-xs clearfix">
  <div class="container">
    <div class="row">
      <div class="col-md-5">
        <div class="header-nav">
          <ul>
            <li><%= link_to t('header.about_us'), aboutus_path %></li>
            <% if user_signed_in? %>
              <li><%= link_to t('header.logout'), destroy_user_session_path, method: :delete %></li>
              <li><%= link_to t('header.member_area'), summary_path %></li>
            <% else %>
              <li><%= link_to t('header.login'), new_user_session_path %></li>
              <li><%= link_to t('header.register'), register_path %></li>
            <% end %>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" id="drop1" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
                <i class="fa fa-chevron-circle-down"></i>
                <%= t('header.language') %>
              </a>
              <ul class="dropdown-menu" aria-labelledby="drop1">
                <li>
                  <%= link_to t('header.english'), root_path(locale: :en) %>
                </li>
                <li>
                  <%= link_to t('header.arabic'), root_path(locale: :ar) %>
                </li>
              </ul>
            </li>
          </ul>
        </div>
      </div>
      <div class="col-md-offset-4 col-md-3 search-sec">
        <div class="input-group">
          <input type="text" class="form-control" placeholder="<%= t('header.search') %>" id="query" name="query" value="">
          <div class="input-group-btn">
            <button type="submit" class="btn btn-danger"><span class="glyphicon glyphicon-search"></span></button>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

<div class="hidden-sm hidden-xs">
  <div class="logo-section">
    <div class="container">
      <div class="row">
        <div class="col-md-3 col-sm-6 col-xs-6">
          <div class="logo">
            <h1><%= t('header.title') %></h1>
            <%= link_to root_path do %>
              <%=image_tag("logo.png", class: "img-responsive")%>
            <% end %>
          </div>
        </div>

        <div class="col-md-offset-0 col-md-9">
          <div class="menuitems">
            <nav class="navbar navbar-default" role="navigation">
              <!--/.navbar-header-->
              <div id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav">
                  <li>
                    <%= link_to t('header.home'), root_path %>
                  </li>
                  <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown"><%= t('header.for_student') %> <b class="caret"></b></a>
                    <ul class="dropdown-menu multi-column columns-3">
                      <div class="row">

                        <div class="col-sm-4">
                          <ul class="multi-column-dropdown">
                            <li><a href="#"><h3><%= t('header.our_services') %></h3></a></li>
                            <li><%= link_to t('header.find_a_tutor'), search_path("q[account_type_eq]": 'Tutor') %></li>
                            <% if user_signed_in? %>
                              <li><%= link_to t('header.tutor_in_your_city'), search_path("q[account_type_eq]": 'Tutor', "q[city_eq]": current_user.city) %></li>
                              <li><%= link_to t('header.browse_tutor'), search_path("q[account_type_eq]": 'Tutor', "q[major_eq]": current_user.major) %></li>
                            <% end %>
                          </ul>
                        </div>

                        <div class="col-sm-4">
                          <ul class="multi-column-dropdown">
                          <li><a href="#"><h3><%= t('header.recent_subjects') %></h3></a></li>
                          <% @recent_students.each do |student| %>
                            <li><%= link_to student.major, search_path("q[account_type_eq]": 'Student', "q[major_eq]": student.major) %></li>
                          <% end %>
                          </ul>
                        </div>

                        <div class="col-sm-4">
                          <ul class="multi-column-dropdown">
                          <li><a href="#"><h3><%= t('header.popular_subjects') %></h3></a></li>
                          <% @popular_majors.each do |major| %>
                            <li><%= link_to major.first, search_path("q[account_type_eq]": 'Student', "q[major_eq]": major.first) %></li>
                          <% end %>
                          </ul>
                        </div>
                      </div>
                    </ul>
                  </li>
                  <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown"><%= t('header.for_tutor') %> <b class="caret"></b></a>
                    <ul class="dropdown-menu multi-column-dropdown">
                      <li><%= link_to t('header.search_for_tutors'), search_path("q[account_type_eq]": 'Tutor') %></li>
                      <% if user_signed_in? %>
                        <li><%= link_to t('header.tutor_in_your_city'), search_path("q[account_type_eq]": 'Tutor', "q[city_eq]": current_user.city) %></li>
                        <li><%= link_to t('header.tutor_with_same_major'), search_path("q[account_type_eq]": 'Tutor', "q[major_eq]": current_user.major) %></li>
                      <% end %>
                    </ul>
                  </li>

                  <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown"><%= t('header.for_employee') %> <b class="caret"></b></a>
                    <ul class="dropdown-menu multi-column-dropdown">
                      <li><%= link_to t('header.search_for_employees'), search_path("q[account_type_eq]": 'Employee/Employer') %></li>
                      <% if user_signed_in? %>
                        <li><%= link_to t('header.employee_in_your_city'), search_path("q[account_type_eq]": 'Employee/Employer', "q[city_eq]": current_user.city) %></li>
                        <li><%= link_to t('header.employee_with_same_job'), search_path("q[account_type_eq]": 'Employee/Employer', "q[job_eq]": current_user.job) %></li>
                      <% end %>
                    </ul>
                  </li>

                  <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown"><%= t('header.for_hobbyist') %> <b class="caret"></b></a>
                    <ul class="dropdown-menu multi-column-dropdown">
                      <li><%= link_to t('header.search_for_hobbyist'), search_path("q[account_type_eq]": 'Hobby') %></li>
                      <% if user_signed_in? %>
                        <li><%= link_to t('header.hobbyist_in_your_city'), search_path("q[account_type_eq]": 'Hobby', "q[city_eq]": current_user.city) %></li>
                        <li><%= link_to t('header.hobbyist_with_same_hobby'), search_path("q[account_type_eq]": 'Hobby', "q[hobbies_cont_any][]": current_user.hobbies) %></li>
                      <% end %>
                    </ul>
                  </li>

                  <li><%= link_to t('header.contact_us'), contactus_path %></li>
                </ul>
              </div>
            </nav>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/shared/_feedback_initializer.html.erb
<% @feedbacks.each do |feedback| %>
  <script type="text/javascript">
    jQuery(function() {
      jQuery('.starbox-<%= feedback.id %>').each(function() {
        var starbox = jQuery(this);
        starbox.starbox({
          average: "<%= feedback.rating %>",
          changeable: false
        });
      });
    });
  </script>
<% end %>

app/views/shared/_flash_messages.html.erb
<div class="clearfix"></div>
<div class="col-md-7 col-md-offset-2 error-div">
  <% flash.each do |type, messages| %>
    <div class="alert alert-<%= type.to_s == 'notice' ? 'success' : 'danger' %> alert-dismissible fade in">
      <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
      <% if messages.present?  and messages.is_a? Array %>
          <% messages.each do |message| %>
            <li><%= display_error_message(message) %></li>
          <% end %>
      <% else %>
         <li><%= messages %></li>
      <% end %>
    </div>
  <% end %>
</div>

app/views/shared/_footer.html.erb
    <div class="clearfix"></div>
    <footer>
      <section class="footer-two">
        <div class="container">
          <div class="new-letter-sec clearfix">
            <h2><%= t('footer.signup') %> <strong><%= t('footer.newsletter') %></strong></h2>
            <div class="col-md-offset-4 col-md-4">
              <div class="input-group">
                <input type="text" class="form-control letterfield" placeholder="<%= t('footer.enter_email') %>" id="query" name="query" value="">
                 <div class="input-group-btn">
                <button type="submit" class="btn btn-letter"><span class="glyphicon glyphicon-send"></span></button>
                </div>
              </div>
            </div>

            <div class="col-md-offset-1 col-md-12 hidden-xs">
              <div class="footer-menu">
                <ul>
                  <li><%= link_to t('footer.home'), root_path %></li>
                  <li><%= link_to t('footer.for_students'), search_path("q[account_type_eq]": 'Student') %></li>
                  <li><%= link_to t('footer.for_tutors'), search_path("q[account_type_eq]": 'Tutor') %></li>
                  <li><%= link_to t('footer.for_employee'), search_path("q[account_type_eq]": 'Employee/Employer') %></li>
                  <li><%= link_to t('footer.for_hobby'), search_path("q[account_type_eq]": 'Hobby') %></li>
                  <li><%= link_to t('footer.contact_us'), contactus_path %></li>
                </ul>
              </div>
            </div>
          </div>
          <!-- news letter sec -->
        </div>
      </section>

      <div class="copy-right">
        <div class="container">
          <div class="row">
            <p><%= t('footer.copyright') %></p>
          </div>
        </div>
      </div>
    </footer>

app/views/shared/_header.html.erb
<header>
  <%= render 'shared/desktop_header' %>
  <%= render 'shared/mobile_header' %>
</header>

app/views/shared/_mobile_header.html.erb
<div class="header-top show-xs hidden-md hidden-lg">
  <div class="container">
    <div class="row">
      <div class="col-xs-7">
        <address><i class="fa fa-envelope"> </i> query@geekrabb.com </address>
      </div>
      <div class="col-xs-5">
        <ul class="social-icons">
          <li><a href="#"><i class="fa fa-facebook"></i></a></li>
          <li><a href="#"><i class="fa fa-twitter"></i></a></li>
          <li><a href="#"><i class="fa fa-linkedin"></i></a></li>
          <li><a href="#"><i class="fa fa-google-plus"></i></a></li>
        </ul>
      </div>
    </div>
  </div>

  <div class="header-2">
    <div class="container">
      <div class="row">
        <div class="col-md-5">
          <div class="header-nav">
            <ul>
              <li><%= link_to t('header.about_us'), aboutus_path %></li>
              <% if user_signed_in? %>
                <li><%= link_to t('header.logout'), destroy_user_session_path, method: :delete %></li>
                <li><%= link_to t('header.member_area'), summary_path %></li>
              <% else %>
                <li><%= link_to t('header.login'), new_user_session_path %></li>
                <li><%= link_to t('header.register'), register_path %></li>
              <% end %>
              <li class="dropdown">
                <a href="#" class="dropdown-toggle" id="drop1" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
                  <i class="fa fa-chevron-circle-down"></i>
                  <%= t('header.language') %>
                </a>
                <ul class="dropdown-menu" aria-labelledby="drop1">
                  <li>
                    <%= link_to t('header.english'), root_path(locale: :en) %>
                  </li>
                  <li>
                    <%= link_to t('header.arabic'), root_path(locale: :ar) %>
                  </li>
                </ul>
              </li>
            </ul>
            <div class="clearfix"></div>
          </div>
        </div>
      </div>
    </div>
  </div>

  <nav class="navbar navbar-default" role="navigation">
    <!--/.navbar-header-->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navbar" aria-expanded="true" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <div class="col-sm-5 col-xs-5">
        <div class="logo">
          <%= link_to root_path do %>
            <%=image_tag("logo.png", class: "img-responsive")%>
          <% end %>
        </div>
      </div>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <li>
          <%= link_to t('header.home'), root_path, class: 'nav-menu' %>
        </li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle nav-menu" data-toggle="dropdown"><%= t('header.for_student') %> <b class="caret"></b></a>
          <ul class="dropdown-menu multi-column columns-3 for-student">
            <div class="row">

              <div class="col-sm-4">
                <ul class="multi-column-dropdown">
                  <li><a href="#"><h3><%= t('header.our_services') %></h3></a></li>
                  <li><%= link_to t('header.find_a_tutor'), search_path("q[account_type_eq]": 'Tutor') %></li>
                  <% if user_signed_in? %>
                    <li><%= link_to t('header.tutor_in_your_city'), search_path("q[account_type_eq]": 'Tutor', "q[city_eq]": current_user.city) %></li>
                    <li><%= link_to t('header.browse_tutor'), search_path("q[account_type_eq]": 'Tutor', "q[major_eq]": current_user.major) %></li>
                  <% end %>
                </ul>
              </div>

              <div class="col-sm-4">
                <ul class="multi-column-dropdown">
                <li><a href="#"><h3><%= t('header.recent_subjects') %></h3></a></li>
                <% @recent_students.each do |student| %>
                  <li><%= link_to student.major, search_path("q[account_type_eq]": 'Student', "q[major_eq]": student.major) %></li>
                <% end %>
                </ul>
              </div>

              <div class="col-sm-4">
                <ul class="multi-column-dropdown">
                <li><a href="#"><h3><%= t('header.popular_subjects') %></h3></a></li>
                <% @popular_majors.each do |major| %>
                  <li><%= link_to major.first, search_path("q[account_type_eq]": 'Student', "q[major_eq]": major.first) %></li>
                <% end %>
                </ul>
              </div>
            </div>
          </ul>
        </li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle nav-menu" data-toggle="dropdown"><%= t('header.for_tutor') %> <b class="caret"></b></a>
          <ul class="dropdown-menu multi-column-dropdown">
            <li><%= link_to t('header.search_for_tutors'), search_path("q[account_type_eq]": 'Tutor') %></li>
            <% if user_signed_in? %>
              <li><%= link_to t('header.tutor_in_your_city'), search_path("q[account_type_eq]": 'Tutor', "q[city_eq]": current_user.city) %></li>
              <li><%= link_to t('header.tutor_with_same_major'), search_path("q[account_type_eq]": 'Tutor', "q[major_eq]": current_user.major) %></li>
            <% end %>
          </ul>
        </li>

        <li class="dropdown">
          <a href="#" class="dropdown-toggle nav-menu" data-toggle="dropdown"><%= t('header.for_employee') %> <b class="caret"></b></a>
          <ul class="dropdown-menu multi-column-dropdown">
            <li><%= link_to t('header.search_for_employees'), search_path("q[account_type_eq]": 'Employee/Employer') %></li>
            <% if user_signed_in? %>
              <li><%= link_to t('header.employee_in_your_city'), search_path("q[account_type_eq]": 'Employee/Employer', "q[city_eq]": current_user.city) %></li>
              <li><%= link_to t('header.employee_with_same_job'), search_path("q[account_type_eq]": 'Employee/Employer', "q[job_eq]": current_user.job) %></li>
            <% end %>
          </ul>
        </li>

        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown"><%= t('header.for_hobbyist') %> <b class="caret"></b></a>
          <ul class="dropdown-menu multi-column-dropdown">
            <li><%= link_to t('header.search_for_hobbyist'), search_path("q[account_type_eq]": 'Hobby') %></li>
            <% if user_signed_in? %>
              <li><%= link_to t('header.hobbyist_in_your_city'), search_path("q[account_type_eq]": 'Hobby', "q[city_eq]": current_user.city) %></li>
              <li><%= link_to t('header.hobbyist_with_same_hobby'), search_path("q[account_type_eq]": 'Hobby', "q[hobbies_cont_any][]": current_user.hobbies) %></li>
            <% end %>
          </ul>
        </li>

        <li><%= link_to t('header.contact_us'), contactus_path %></li>
      </ul>
    </div>
  </nav>

  <div class="header-2">
    <div class="container">
      <div class="row">
        <div class="col-sm-12 col-xs-12 search-sec">
          <div class="input-group">
            <input type="text" class="form-control" placeholder="<%= t('header.search') %>" id="query" name="query" value="">
            <div class="input-group-btn">
              <button type="submit" class="btn btn-danger"><span class="glyphicon glyphicon-search"></span></button>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/shared/_navigation-bar.html.erb
<div class="col-md-12">
  <h4 class="heading2"><%= t('navigation_bar.title') %></h4>
</div>
<div class="col-md-3 col-sm-4">
  <div class="member-left-area">
    <ul class="member-list">
      <li class="<%= current_page_class('summary') %>">
        <%= link_to summary_path do %>
          <i class="fa fa-home"></i> <%= t('navigation_bar.summary') %>
        <% end %>
      </li>
      <li class="<%= current_page_class('mydetail') %>">
        <%= link_to mydetail_path do %>
          <i class="fa fa-user"></i> <%= t('navigation_bar.mydetail') %>
        <% end %>
      </li>
      <% if current_user.tutor? %>
        <li class="<%= current_page_class('mysubject') %>">
          <%= link_to mysubject_path do %>
            <i class="fa fa-suitcase" aria-hidden="true"></i> <%= t('navigation_bar.my_subjects') %>
          <% end %>
        </li>
      <% end %>

      <% if current_user.student? || current_user.tutor? %>
        <li class="<%= current_page_class('mypurchase') %>">
          <%= link_to mypurchase_path do %>
            <span class="glyphicon glyphicon-edit" aria-hidden="true"></span> <%= t('navigation_bar.mypurchases') %>
          <% end %>
        </li>
      <% end %>

      <li class="<%= current_page_class('feedback') %>">
        <%= link_to feedback_section_path do %>
          <span class="glyphicon glyphicon-pencil" aria-hidden="true"> </span> <%= t('navigation_bar.feedback') %>
        <% end %>
      </li>

      <% if current_user.student? || current_user.tutor? %>
        <li class="<%= current_page_class('found_me') %>">
          <%= link_to found_me_path do %>
            <span class="glyphicon glyphicon-search" aria-hidden="true"></span> <%= t('navigation_bar.found_me') %>
          <% end %>
        </li>
      <% end %>

      <% if current_user.student? %>
        <li class="<%= current_page_class('suggested_teacher') %>">
          <%= link_to suggested_teacher_path do %>
            <span class="glyphicon glyphicon-briefcase" aria-hidden="true"> </span> <%= t('navigation_bar.suggested_teacher') %>
          <% end %>
        </li>
      <% end %>
      <% unless current_user.employee? || current_user.hobby? %>
        <li class="<%= current_page_class('followers') %>">
          <%= link_to followers_path do %>
            <span class="glyphicon glyphicon-star" aria-hidden="true"> </span> <%= t('navigation_bar.followers') %>
          <% end %>
        </li>
      <% end %>

      <li style="border-bottom:1px solid #d2d2d2;">
        <%= link_to destroy_user_session_path, method: :delete do %>
          <span class="fa fa-power-off" aria-hidden="true"></span> <%= t('navigation_bar.logout') %>
        <% end %>
      </li>
    </ul>
  </div>
</div>