config/routes.rb
Rails.application.routes.draw do

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  apipie

  get '/user_info_for_chat' => 'users#info_for_chat', format: :js

  scope '(:locale)' do
    get 'users/sign_up' => 'home#register'
  end

  devise_for :users, controllers: {sessions: "sessions"}

  namespace :api, defaults: {format: 'json'} do
    scope module: :v1, constraints: ApiConstraints.new(version: 1, default: true) do
      devise_for :users, only: [:sessions, :registrations ], controllers: {sessions: 'api/v1/devise/sessions', registrations: 'api/v1/devise/registrations'}
      resources :users do
        get :default_values, on: :collection
        get :search, on: :collection
        get :me, on: :collection
        get :display_contact_info, on: :collection
        post :verify_payment, on: :collection
        get :verify_account, on: :collection
        get :resend_verification_code, on: :collection
        get :subscribe_for_notification, on: :collection
        get :reset_password, on: :collection
        post :update_password, on: :collection
        post :update_profile, on: :collection
        put :update_user, on: :collection
        post :send_notification, on: :collection
      end

      resources :conversations, only: [:index, :create, :show, :destroy] do
        get :latest_messages
        post :read
        collection do
          get :unread_count
        end
      end
      resources :messages, only: [:create]
      resources :contacts, only: [:create]
      resources :feedbacks, only: [:create]
      resources :activities do
        member do
          get :join
          get :leave
        end
      end
    end
  end

  scope '(:locale)' do
    resources :users do
      post :update_payment_status
      get :get_contact_info, format: :js
      get :follow, format: :js
      get :unfollow, format: :js
    end

    resources :conversations do
      resources :messages
    end

    resources :feedbacks

    # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
    root "home#index"
    get "/register" => 'home#register'
    post "/register_user" => 'home#register_user', format: :js
    post "/verify_code" => 'home#verify_code', format: :js
    get "/verify" => 'users#verify_phone_number', as: 'new_verify'
    post '/verify' => 'users#resend_code', as: 'resend_verify'
    put '/verify' => 'users#verify_code', as: 'verify'
    get "/summary" => 'home#summary'
    get "/search" => 'home#search'
    post "/search" => 'home#search'
    get "/mydetail" => 'home#mydetail'
    get "/mysubject" => 'home#mysubject'
    get "/myenquiry" => 'home#myenquiry'
    get "/mypurchase" => 'home#mypurchase'
    get "/online-lesson" => 'home#online_lesson'
    get "/feedback_section" => 'home#feedback_section'
    get "/found-me" => 'home#found_me'
    get "/suggested-teacher" => 'home#suggested_teacher'
    get "/profile-photo" => 'home#profile_photo'
    get "/post-question" => 'home#post_question'
    get "/followers" => 'home#followers'
    get "/tags" => 'home#tags'
    get "/history" => 'home#history'
    get "/privacy" => 'home#privacy'
    get "/contactus" => 'home#contactus'
    get "/aboutus" => 'home#aboutus'
    get "/payment" => 'home#payment'
  end
end

app/controllers/home_controller.rb
require 'nexmo'
class HomeController < ApplicationController

  skip_before_filter :redirect_if_unverified, only: [:register, :register_user]
  before_action :authenticate_user!, except: [:index, :register, :register_user, :contactus, :aboutus, :verify_code]
  before_action :set_page

  def index
    @q = User.ransack(params[:q])
  end

  def register
    @user = User.new
  end

  def register_user
    @user = User.new(user_params)
    if @user.save
      @user.create_openfire_user(user_params[:password])
      if @user.tutor?
        flash[:notice] = "Successfully Registered User"
      else
        @user.send_pin!
      end
    else
      @user.date_of_birth_validness(user_params[:date_of_birth])
      @errors = @user.errors.full_messages.to_sentence
    end
  end

  def verify_code
    @user = User.find_by(id: params[:user_id])

    if Time.now > @user.pin_sent_at.advance(minutes: 60)
      @verified = false
    elsif params[:code].try(:to_i) == @user.pin
      @verified = true
      @user.update(verified: true)
    else
      @verified = false
    end
  end

  def search
    params[:q] = {} if params[:q].blank?
    params[:q][:id_not_eq] = current_user.id
    @q = User.ransack(params[:q])

    @users = @q.result.includes(:photo).page(params[:page]).per(User::PER_PAGE)
  end

  def summary
  end

  def mydetail
    current_user.build_photo if current_user.photo.blank?
  end

  def mysubject
  end

  def myenquiry
  end

  def mypurchase
    @payments = current_user.payments.successfull
  end

  def online_lesson
  end

  def feedback_section
    @feedbacks = Feedback.where(rated_id: current_user.id).includes(:user)
  end

  def found_me
    @profile_views = ProfileView.includes(:user).where(user_viewed_id: current_user.id)
    @this_months_views = @profile_views.this_month
    @recent_views = @profile_views.recents
  end

  def suggested_teacher
    params[:q] = {}
    params[:q][:id_not_eq] = current_user.id
    params[:q][:account_type_eq] = current_user.account_type
    params[:q][:city_eq] = current_user.city
    params[:q][:major_eq] = current_user.major
    params[:q][:teaching_modules_in] = current_user.teaching_modules
    params[:q][:job_eq] = current_user.job
    params[:q][:hobbies_cont_any] = current_user.hobbies

    @q = User.ransack(params[:q])
    @users = @q.result.page(params[:page]).per(7)
  end

  def profile_photo
  end

  def post_question
  end

  def followers
    @followees = current_user.followees(User)
  end

  def tags
  end

  def history
  end

  def privacy
  end

  def contactus
  end

  def aboutus
  end

  def payment
    @current_user = current_user
  end

  private

  def set_page
    @current_page = params[:action]
  end

  def user_params
    params.require(:user).permit(:first_name, :last_name, :email, :user_name, :password, :account_type, :gender, :date_of_birth, :city, :education_level, :institution, :major, :availablity_start_time, :availablity_end_time, :hourly_rate, :other_institute, :nationality, :work_experience, :job, :other_major, :interested_in_online_teachings, :interested_in_online_lessons, :mobile_number, teaching_interests: [], languages: [], teaching_modules: [], hobbies: [], degrees_attributes: [:id, :name, :institution, :other_institute, :avatar, :_destroy])
  end

end

app/views/home/_error_messages.html.erb
<div class="modal fade contact-info" id="error-modal">
  <div class="modal-header">
    <button aria-hidden="true" class="close" data-dismiss="modal" type="button">×</button>
    <h3 id="myModalLabel">Failed to Registered User</h3>
  </div>

  <div class="modal-body">
    <%= @errors %>
  </div>

  <div class="modal-footer">
    <button aria-hidden="true" class="btn" data-dismiss="modal">Close</button>
  </div>
</div>

app/views/home/_tutor_verification.html.erb
<div class="modal fade contact-info" id="tutor-verification-modal" title="Tutor account verification for <%= @user.username %>">
  <div class="modal-header">
    <button aria-hidden="true" class="close" data-dismiss="modal" type="button">×</button>
    <h3 id="myModalLabel">Successfully Registered User</h3>
  </div>

  <div class="modal-body">
  Thank you for registering you account. Your account will be verified soon by admin.
  </div>

  <div class="modal-footer">
    <%= link_to 'Close', root_path, class: "btn" %>
  </div>
</div>

app/views/home/aboutus.html.erb
<section class="agency-status" style="padding:50px 0">
  <div class="container">
    <div class="col-md-12">
      <h2 class="redcolor"><%= t('about_us.title') %></h2>
      <p><%= t('about_us.para_one') %></p>
      <p><%= t('about_us.para_two') %></p>
    </div>
  </div>
</section>

app/views/home/contactus.html.erb
<section class="agency-status" style="padding:50px 0">
  <div class="container">
    <div class="row">
      <div class="finish-box-shadow clearfix">
        <div class="col-md-6 col-md-offset-3 tutor-img">
          <!-- <h2 class=""></h2> -->
          <div class="panel heading-bg">
            <p><%= t('contact.title') %></p>
            <div class="panel-heading">
              <h3 class="panel-title white-text"><%= t('contact.geekrabb') %></h3>
            </div>
            <div class="panel-body">
              <form class="form-horizontal">
                <div class="form-group">
                  <label for="inputEmail3" class="col-sm-3 control-label"><%= t('contact.form.name') %></label>
                  <div class="col-sm-9">
                    <input class="form-control darker-boarder" id="inputYour Name" placeholder="<%= t('contact.form.name') %>" required>
                  </div>
                </div>
                <div class="form-group">
                  <label for="inputPassword3" class="col-sm-3 control-label"><%= t('contact.form.email') %></label>
                  <div class="col-sm-9">
                    <input type="email" class="form-control darker-boarder" id="inputPassword3" placeholder="<%= t('contact.form.email') %>" required>
                  </div>
                </div>
                <div class="form-group">
                  <label for="inputPassword3" class="col-sm-3 control-label"><%= t('contact.form.message') %></label>
                  <div class="col-sm-9">
                    <textarea name="" id="" cols="30" rows="8" class="form-control darker-boarder" required></textarea>
                  </div>
                </div>
                <div class="form-group">
                  <div class="col-sm-offset-3 col-sm-10">
                    <button type="submit" class="btn btn-danger"><%= t('contact.form.send') %></button>
                  </div>
                </div>
              </form>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

app/views/home/history.html.erb
<section class="member" style="padding:50px 0">
  <div class="container">
    <div class="row">

      <%= render 'shared/navigation-bar' %>

      <div class="col-md-8 col-sm-8">
        <div class="profile-photo">
          <p>Here you can view your history in terms of whose profile pages you have recently viewed, the most recent viewed is at the top of the list. You can clear your history here, or if you would prefer not to have your history stored you can change this setting in the <a href="privacy.html" class="redcolor"> Privacy </a> section.</p>
          <p class="redcolor">Your History is Empty.</p>
        </div>
      </div>
    </div>
  </div>
</section>

app/views/home/myenquiry.html.erb
<section class="member" style="padding:50px 0">
  <div class="container">
    <div class="row">

      <%= render 'shared/navigation-bar' %>

      <div class="col-md-8 col-sm-8">
        <div class="mysubjects">
          <div class="dropdown">
            <button class="btn btn-default dropdown-toggle" type="button" id="enquiry" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">
              Open Enquiries
              <span class="caret"></span>
            </button>
            Now Viewing:
            <ul class="dropdown-menu" aria-labelledby="enquiry">
              <li><a href="#">Open Enquiries</a></li>
              <li><a href="#">Close Enquiries</a></li>
            </ul>
          </div>
          <p style="margin-top:15px;"><span class="glyphicon glyphicon-plus-sign" style="color:#f85862"> </span>  To make a new enquiry please <a href="#" style="color:#f85826;">search</a>  and contact via their profile page.</p>
        </div>
      </div>
    </div>
  </div>
</section>

app/views/home/mypurchase.html.erb
<section class="member" style="padding:50px 0">
  <div class="container">
    <div class="row">

      <%= render 'shared/navigation-bar' %>

      <div class="col-md-8 col-sm-8">
        <% if @payments.present? %>
          <div class="foundme">
            <p><%= t('purchases.title') %></p>

            <table class="table table-bordered">
              <tbody>
                <tr style="background: #666666;color: #fff;text-transform: uppercase;">
                  <td colspan="3"><%= t('purchases.payments') %></td>
                </tr>

                <tr>
                  <td><%= t('purchases.type') %></td>
                  <td><%= t('purchases.amount') %></td>
                  <td><%= t('purchases.time') %></td>
                </tr>

                <% @payments.each do |payment| %>
                  <tr>
                    <td><span class="glyphicon glyphicon-credit-card"></span> <%= payment.payment_type %></td>
                    <td>
                      $10
                    </td>
                    <td>
                      <%= formatted_time(payment.created_at) %>
                    </td>
                  </tr>
                <% end %>
              </tbody>
            </table>
          </div>
        <% else %>
          <div class="mysubjects">
            <p><%= t('purchases.all_purchases') %></p>
            <p style="margin-top:15px; color:#f85826;"><%= t('purchases.no_purchases') %></p>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</section>

app/views/home/online_lesson.html.erb
<section class="member" style="padding:50px 0">
  <div class="container">
    <div class="row">

      <%= render 'shared/navigation-bar' %>

      <div class="col-md-8 col-sm-8">
        <div class="mysubjects">
          <div class="lesson-contents">
            <ul class="nav nav-tabs" role="tablist">
              <li role="presentation" class="active"><a href="#home" aria-controls="home" role="tab" data-toggle="tab">
              <span class="glyphicon glyphicon-blackboard" aria-hidden="true"></span> My Online lessons</a></li>
              <li role="presentation"><a href="#profile" aria-controls="profile" role="tab" data-toggle="tab">
              <span class="glyphicon glyphicon-pencil" aria-hidden="true"> </span> Create Lessons</a></li>
              <li role="presentation"><a href="#messages" aria-controls="messages" role="tab" data-toggle="tab">
              <span class="glyphicon glyphicon-question-sign" aria-hidden="true"></span> How It works</a></li>
              <li role="presentation"><a href="#settings" aria-controls="settings" role="tab" data-toggle="tab">
              <span class="glyphicon glyphicon-search" aria-hidden="true"></span> Find a tutor</a></li>
            </ul>

            <div class="tab-content">
              <div role="tabpanel" class="tab-pane active" id="home">
                <div class="myonline-lessons-contents">
                  <p>My Online Lessons <span class="glyphicon glyphicon-plus-sign" style="color:#f85862"> </span>  Add New Online Lessons</p>
                  <div class="member-area-content-bg">
                      <p>If you have used our service to find a tutor you can click on above link to start online lessons with them. Otherwise you need to first find a tutor using our <a href="#" style ="color:#f86852;"">Search</a> and book a lesson with them.</p>
                  </div>
                </div>
              </div>
            <div role="tabpanel" class="tab-pane" id="profile">
              <h4 class="heading2">Start New Online Lessons</h4>
              <p>
              To start online lessons with a new tutor, you must first contact the tutor by using our search. The tutors details will appear below once you've made an initial booking.
              </p>
            </div>
            <div role="tabpanel" class="tab-pane" id="messages"></div>
            <div role="tabpanel" class="tab-pane" id="settings">
              <section class="search-section" style="background:none;">
                <div class="row">
                  <h2>Find the right tutor for you</h2>
                  <div class="search-form">
                    <form method="post">
                      <div class="col-md-3">
                        <input type="email" class="form-control" id="exampleInputEmail3" placeholder="Enter subjects">
                      </div>
                      <div class="col-md-3">
                        <select class="form-control">
                          <option>Select Level</option>
                          <option>2</option>
                          <option>3</option>
                          <option>4</option>
                          <option>5</option>
                        </select>
                      </div>
                      <div class="col-md-3">
                        <input type="text" class="form-control" id="exampleInputPassword3" placeholder="Postcode">
                      </div>
                      <div class="col-md-3">
                        <button type="submit" class="form-control btn btn-danger">Search</button>
                      </div>
                    </form>
                  </div>
                </div>
              </section>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

app/views/home/post_question.html.erb
<section class="member" style="padding:50px 0">
  <div class="container">
    <div class="row">

      <%= render 'shared/navigation-bar' %>

      <div class="col-md-8 col-sm-8">
        <div class="profile-photo">
          <div class="member-area-content-bg">
            <p>We have thousands of tutors registered here at Tutor Hunt, our Questions portal allow students to pose any academic query they have directly to them. Once you submit a question we will publish it, and allow any of our wide range of tutors to answer it for you. You can also manage your previously asked questions here.</p>
          </div>
          <strong>My Questions</strong> <a href="ask-question.html" class="redcolor"><span class="glyphicon glyphicon-plus-sign redcolor"></span> <span>Ask an Academic Question</span></a>
          <p class="round-bg">You have currently not asked any academic questions, would you like to <a href="ask-question.html" class="redcolor"> ask a question? </a> </p>
          <div class="panel panel-default heading-panel">
            <div class="panel-heading">UPLOAD YOUR PHOTO</div>
            <div class="panel-body">
              <label class="btn btn-default btn-file">
                Browse <input type="file" hidden>
              </label>
              <p>You have not uploaded any photos for your profile yet.</p>
              <br/>
              <span class="glyphicon glyphicon-plus-sign redcolor"></span> <a href="#" class="redcolor">Cancel</a> Photo Upload - Return to my Photos Page
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

app/views/home/profile_photo.html.erb
<section class="member" style="padding:50px 0">
  <div class="container">
    <div class="row">

      <%= render 'shared/navigation-bar' %>

      <div class="col-md-8 col-sm-8">
        <div class="profile-photo">
          <p>Here are your current uploaded photos, click on a photo to make changes to it or set it as your profile image. Your current profile image is marked by a wide blue border.</p>
          <p><a href="upload-img.html" class="redcolor"><span class="glyphicon glyphicon-plus-sign"> </span> Upload Photos</a></p>
          <div class="panel panel-default heading-panel">
            <div class="panel-heading">SELECT A PHOTO</div>
            <div class="panel-body">
              <p>You have not uploaded any photos for your profile yet.</p>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

app/views/home/search.html.erb
<section class="agency-status" style="padding:50px 0">
  <div class="container">
    <div class="row">
      <div class="col-md-8 col-sm-8">
        <div class="row">
          <div class="col-md-12">
            <h2 class="redcolor"><%= t('search.title') %></h2>
            <% if @users.present? %>
              <p><%= t('search.non_logged_in.you_must') %> <span class="blue"><%= t('search.non_logged_in.signup') %></span> <%= t('search.non_logged_in.contact_member') %> </p>
            <% else %>
              <p><%= t('search.no_result') %></p>
            <% end %>
          </div>
        </div>

        <div class="search_circle"></div>
        <div class="row">

          <% @users.each do |user| %>
            <div class="col-sm-6 searchresult text-center">
              <%= image_tag fetch_photo(user, :profile), class: 'img-circle name-profile' %>
              <p class="text-center"><%= user.first_name %> <%= user.last_name %> <%= t('search.miles_away') %>         |    <span class="glyphicon glyphicon-map-marker"> </span> <%= user.city %>        </p>
              <p class="text-center"><%= t('search.fully_committed') %> </p>
              <p class="extra-margin">
              <%= link_to t('search.profile'), user_path(user), class: "btn btn-danger" %>
              <button type="button" data-username="<%= user.jid %>"  class="btn btn-warning start-conversation" data-sid="<%= current_user.id %>" data-rip="<%=user.id %>"><span class="glyphicon glyphicon-comment"></span> <%= t('search.chat') %></button>

              <% if current_user.follows?(user) %>
                <%= link_to "#{ t('search.unfollow') }", user_unfollow_path(user, id: user.id, format: :js), class: "btn btn-default", remote: true %>
              <% else %>
                <%= link_to "#{ t('search.follow') }", user_follow_path(user, id: user.id, format: :js), class: "btn btn-info", remote: true %>
              <% end %>

              <% if user.tutor? %>
                <button type="button" class="btn btn-default"> <span class="glyphicon glyphicon-usd"></span> <%= user.hourly_rate %>/h </button>
              <% end %>
              </p>
            </div>
          <% end %>
        </div>
        <%= paginate @users %>
      </div>
      <div class="col-md-4 col-sm-4">
        <div class="right-side">
          <div class="search-form">
            <ul class="nav nav-tabs search-nav-tab" role="tablist">
              <li role="presentation" class="active"><a href="#home" aria-controls="home" role="tab" data-toggle="tab">
              <span class="glyphicon glyphicon-search" aria-hidden="true"></span> <%= t('search.search') %></a></li>
            </ul>

            <div class="tab-content searchform">
              <div role="tabpanel" class="tab-pane active" id="home">
                <div class="myonline-lessons-contents">

                  <%= search_form_for @q, url: search_path do |f| %>
                    <div class="form-group" id="q_first_name_cont_div">
                      <%= f.label t('search.form.labels.first_name') %>
                      <%= f.search_field :first_name_cont, class: "form-control form-bg", placeholder: "#{ t('search.form.placeholders.first_name') }" %>
                    </div>

                    <div class="form-group" id="q_last_name_cont_div">
                      <%= f.label t('search.form.labels.last_name') %>
                      <%= f.search_field :last_name_cont, class: "form-control form-bg", placeholder: "#{ t('search.form.placeholders.last_name') }" %>
                    </div>

                    <div class="form-group" id="q_gender_eq_div">
                      <%= f.label t('search.form.labels.gender') %>
                      <%= select_tag 'q[gender_in][]', options_for_select(options_for_gender.collect{|s| [s[I18n.locale], s[:en]]}, preselect_gender_value), class: 'form-control form-bg multiple-selected', multiple: 'multiple', data: { placeholder: "#{ t('search.form.placeholders.gender') }", select_all: "#{ t('home.select_all') }", select_all: "#{ t('home.select_all') }" } %>
                    </div>

                    <div class="form-group">
                      <%= f.label t('search.form.labels.account') %>
                      <%= select_tag 'q[account_type_eq]', options_for_select(options_for_account_type.collect{|s| [s[I18n.locale], s[:en]]}, preselect_account_value), prompt: "#{ t('search.form.placeholders.account') }", class: 'form-control form-bg' %>
                    </div>

                      <div class="form-group" id="q_hobbies_cont_div">
                        <%= f.label t('search.form.labels.hobby') %>
                        <%= select_tag 'q[hobbies_cont_any][]', options_for_select(options_for_hobbies.collect{|s| [s[I18n.locale], s[:en]]}, preselect_hobbies_value), class: 'form-control form-bg multiple-selected', multiple: "multiple" %>
                      </div>

                      <div class="form-group" id="q_job_cont_div">
                        <%= f.label t('search.form.labels.job') %>
                        <%= f.search_field :job_cont, class: "form-control form-bg", placeholder: "#{ t('search.form.placeholders.job') }" %>
                      </div>

                      <div class="form-group" id="q_education_level_eq_div">
                        <%= f.label t('search.form.labels.education_level') %>
                        <%= select_tag 'q[education_level_in][]', options_for_select(options_for_education_level.collect{|s| [s[I18n.locale], s[:en]]}, preselect_education_level_value), class: 'form-control form-bg multiple-selected', multiple: 'multiple', data: { placeholder: "#{ t('search.form.placeholders.education_level') }", select_all: "#{ t('home.select_all') }" } %>
                      </div>


                      <div class="form-group" id="q_teaching_modules_cont_div">
                        <%= f.label t('search.form.labels.teaching_module') %>
                        <%= f.search_field :teaching_modules_cont, class: "form-control form-bg", placeholder: "#{ t('search.form.placeholders.teaching_module') }" %>
                      </div>

                      <div class="form-group" id="q_major_cont_div">
                        <%= f.label t('search.form.labels.major') %>
                        <%= f.search_field :major_cont, class: "form-control form-bg", placeholder: "#{ t('search.form.placeholders.major') }" %>
                      </div>

                    <div class="form-group" id="q_city_eq_div">
                      <%= f.label t('search.form.labels.city') %>
                      <%= select_tag 'q[city_in][]', options_for_select(options_for_city.collect{|s| [s[I18n.locale], s[:en]]}, preselect_city_value), class: 'form-control form-bg multiple-selected', multiple: 'multiple', data: { placeholder: "#{ t('search.form.placeholders.city') }", select_all: "#{ t('home.select_all') }" } %>
                    </div>

                    <p class="text-center">
                      <%= f.submit "#{ t('search.search') }", class: 'btn btn-danger search-btn text-center' %>
                    </p>
                  <% end %>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

<div id='follow-unfollow-div'></div>

<% content_for :js_init do %>
  Search.bind_multiselect();
  Search.init();
<% end %>

app/views/home/tags.html.erb
<section class="member" style="padding:50px 0">
  <div class="container">
    <div class="row">

      <%= render 'shared/navigation-bar' %>

      <div class="col-md-8 col-sm-8">
        <div class="profile-photo">
          <p>Here are all your tagged Tutor Hunt users. These are your users you are interested in, so you can easily remember them at a later date for contact. This list is private to you and will not show in your profile.</p>
          <p class="redcolor">No users are tagged</p>
        </div>
      </div>
    </div>
  </div>
</section>